Implement fetching

diff --git a/kubectl-gopass b/kubectl-gopass
--- a/kubectl-gopass
+++ b/kubectl-gopass
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-VERSION='0.0.4'
+VERSION='0.1.0'
 
 set -euo pipefail
 
@@ -27,11 +27,19 @@ Usage:
     create a new secret prefilled with a kubernetes secret template and starts
     an editor to edit the newly created secret
 
+# kubectl gopass fetch [optional kubectl get secret params] secret-name dir/to/gopass-secret
+    fetches a secret with name from the kubernetes cluster and stores in in gopass as dir/to/gopass-secret
+
+# kubectl gopass fetchrecursive [optional kubectl get secret params] dir/to/gopass-secret-path
+    fetches all secrets from the kubernetes cluster (namespace) and stores them in gopass dir/to/gopass-secret-path
+
 # kubectl gopass version
     prints out the kubectl-gopass version ($VERSION)
 
 # kubectl gopass help
     prints these usage instructions
+
+Gopass and kubectl is required for all functionality, jq and yq are required for fetching secrets from kubernetes to gopass.
 
 EOF
 }
@@ -97,6 +105,57 @@ EOL
   exit 0
 }
 
+fetch() {
+  if [[ "$#" -lt 3 ]]; then
+    echo >&2 "Too few arguments, kubernetes secret and target gopass secret is required"
+    usage
+    exit 1
+  fi
+  SECRET="${*: (-2):1}"
+  TARGET="${*: -1}"
+
+  KUBECTL_ARGS=("$@")
+  unset "KUBECTL_ARGS[${#KUBECTL_ARGS[@]}-1]"
+  unset "KUBECTL_ARGS[0]"
+  LEN_KUBECTL_ARGS=${#KUBECTL_ARGS[@]}
+  if [[ "$LEN_KUBECTL_ARGS" -lt 1 ]]; then
+    echo "will fetch secret $SECRET"
+  else
+    echo "will fetch secret $SECRET with additional kubectl args '" "${KUBECTL_ARGS[@]}" "'"
+  fi
+  $KUBECTL get secret ${KUBECTL_ARGS[@]+"${KUBECTL_ARGS[@]}"} $SECRET -o json | \
+  $JQ 'del(.metadata.creationTimestamp)|del(.metadata.resourceVersion)|del(.metadata.selfLink)|del(.metadata.uid)|.data[] |= @base64d | . + {"stringData": .data} | del(.data)' | \
+  $YQ read - | \
+  $GOPASS insert "${TARGET}"
+}
+
+fetchrecursive() {
+  if [[ "$#" -lt 2 ]]; then
+    echo >&2 "Too few arguments, target gopass path is required"
+    usage
+    exit 1
+  fi
+  TARGET="${*: -1}"
+
+  KUBECTL_ARGS=("$@")
+  unset "KUBECTL_ARGS[${#KUBECTL_ARGS[@]}-1]"
+  unset "KUBECTL_ARGS[0]"
+  LEN_KUBECTL_ARGS=${#KUBECTL_ARGS[@]}
+  if [[ "$LEN_KUBECTL_ARGS" -lt 1 ]]; then
+    echo "will fetch secrets to  $TARGET"
+  else
+    echo "will fetch secrets to  $TARGET with additional kubectl args '" "${KUBECTL_ARGS[@]}" "'"
+  fi
+
+  for SECRET in $($KUBECTL get secrets -o json | $JQ -r ".items[].metadata.name"); do
+    echo "fetching ${SECRET}"
+    $KUBECTL get secret ${KUBECTL_ARGS[@]+"${KUBECTL_ARGS[@]}"} $SECRET -o json | \
+    $JQ 'del(.metadata.creationTimestamp)|del(.metadata.resourceVersion)|del(.metadata.selfLink)|del(.metadata.uid)|.data[] |= @base64d | . + {"stringData": .data} | del(.data)' | \
+    $YQ read - | \
+    $GOPASS insert "${TARGET}/${SECRET}"
+  done
+}
+
 main() {
   if hash kubectl 2>/dev/null; then
     KUBECTL=kubectl
@@ -114,6 +173,18 @@ main() {
   else
     echo >&2 "gopass is not installed"
     exit 1
+  fi
+
+  if hash jq 2>/dev/null; then
+    JQ=jq
+  else
+    echo >&2 "jq is not installed, fetching secrets from kubernetes to gopass will not work"
+  fi
+
+  if hash yq 2>/dev/null; then
+    YQ=yq
+  else
+    echo >&2 "yq is not installed, fetching secrets from kubernetes to gopass will not work"
   fi
 
   if [[ "$#" -eq 0 ]]; then
@@ -137,6 +208,12 @@ main() {
     ;;
   'create')
     create "${@:1}"
+    ;;
+  'fetch')
+    fetch "${@:1}"
+    ;;
+  'fetch-recursive')
+    fetchrecursive "${@:1}"
     ;;
   'version')
     echo "$VERSION"
